AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with hello world.
Resources:
  LambdaHello:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        ZipFile: release.zip
      Environment: 
        Variables: 
          PERSON_NAME : Smith
      Handler: index.lambda_handler
      Role: !Ref LambdaHelloIamRole
      Runtime: nodejs
      PackageType: Zip
      TracingConfig:
        Mode: Active
  
  LambdaHelloIamRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Allow lamda function for cloud watch logs
      ManagedPolicyArns: 
        - arn:aws:iam::592483804673:policy/service-role/AWSLambdaBasicExecutionRole-88015cf9-c110-44ed-9adb-889fd7a089f5