name: lambda-deployment

on: 
  push:
    branches:
        main 
  
jobs:
  lambda-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install npm dependencies
        run: npm ci
    
      - uses: actions/checkout@v1
      - name: Zip Folder
        run: zip -r release.zip . -x ".git/*" ".github/*"
     
