name: lambda-deployment

on: 
  push:
    branches:
        main 
  
jobs:
  lambda-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install  dependencies and zip project
        uses: qoqa/action-s3-cp@v1.1
        run: |
          npm ci
          zip -r index.zip . -x ".git/*" ".github/*"
          ls
         
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          
      - name: Create S3 Bucket
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: DeployArtifact
          template: pre-deploy.yaml

      - name: Push Zip to S3
        uses: jakejarvis/s3-sync-action@v0.3.1
        env:
          SOURCE_DIR: './index.zip'
          AWS_REGION: 'eu-west-1'
          AWS_S3_BUCKET: 'devops-academy-lambda-artifacts-schneider'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: DeployStack
          template: template.yaml
     
     
